# Generated by Django 3.2.3 on 2021-05-16 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50, null=True)),
                ('color_bus', models.CharField(max_length=50, null=True)),
                ('number_seat', models.IntegerField(default='', null=True)),
                ('model_bus', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Captin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField(default='', null=True)),
                ('to_address', models.TextField(null=True)),
                ('from_date', models.TextField(null=True)),
                ('to_date', models.TextField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl.bus')),
                ('captin', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captin_name', to='swvl.captin')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=100)),
                ('rate', models.CharField(max_length=10, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swvl.passenger')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swvl.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_seats', models.IntegerField(null=True)),
                ('from_address', models.TextField(null=True)),
                ('to_address', models.TextField(null=True)),
                ('date_For_start_trip', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 16, 12, 38, 47, 204600))),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='swvl.passenger')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl.trip')),
            ],
        ),
    ]
