# Generated by Django 3.2.3 on 2021-05-20 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl', '0003_auto_20210517_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='namw',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 13, 46, 57, 695675)),
        ),
    ]
