# Generated by Django 3.2.3 on 2021-06-13 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl', '0006_auto_20210520_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 19, 59, 52, 413874)),
        ),
    ]
