# Generated by Django 3.2.3 on 2021-06-25 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl', '0008_auto_20210623_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 18, 14, 25, 641485)),
        ),
    ]
