# Generated by Django 3.2.3 on 2021-07-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swvl', '0019_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
